spring:
  application:
    name: signaling-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfu?useSSL=false
      &serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
      &allowPublicKeyRetrieval=true
    username: sfu_user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # 개발: update / 운영: validate or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

mediasoup:
  sfu-server-url: "http://127.0.0.1:3001"
  worker-settings:
    rtc-min-port: 10000
    rtc-max-port: 10100

logging:
  level:
    com.signaling: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
